# Generated by Django 6.0.4 on 2026-04-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(choices=[('Under 18', 'Under 18'), ('18-24', '18-24'), ('25-34', '25-34'), ('35+', '35+')], max_length=20)),
                ('favorite_genre', models.CharField(choices=[('Action', 'Action'), ('Romance', 'Romance'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror'), ('Slice of Life', 'Slice of Life')], max_length=50)),
                ('watching_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Several times a week', 'Several times a week'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Occasionally', 'Occasionally')], max_length=50)),
                ('favorite_anime', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='anime_genre',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='answer',
        ),
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feature',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
